[[redirects]]
from = "https://mark1.netlify.app/"
to = "https://andreasmaerki.dev/"
status = 301
force = true

[[redirects]]
from = "https://mark1.netlify.app/*"
to = "https://andreasmaerki.dev/:splat"
  status = 301
  force = true
