[[redirects]]
from = "https://mark1.netlify.app/"
to = "https://andreasmaerki.dev/"
status = 301
force = true

[[redirects]]
from = "https://mark1.netlify.app/*"
to = "https://andreasmaerki.dev/:splat"
status = 301
force = true

# SPA fallback for React Router
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
publish = "build"

# Headers for better Safari performance and animation support
[[headers]]
for = "/*"
[headers.values]
# Enable high-resolution timers for smoother animations
Cross-Origin-Opener-Policy = "same-origin"
Cross-Origin-Embedder-Policy = "require-corp"
# Cache optimization
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/index.html"
[headers.values]
# Don't cache the main HTML file
Cache-Control = "public, max-age=0, must-revalidate"
# Enable high-resolution timers
Cross-Origin-Opener-Policy = "same-origin"
Cross-Origin-Embedder-Policy = "require-corp"
